### ISSUE TITLE
[V1.0.0] Image doesn't display after dismiss from fullScreenViewController with image preload

### ISSUE THREAD

**Issue by shawn-shen** [zvonicek/ImageSlideshow#114]
Steps to reproduce:
1. Set preload as 3 and load 15 images into slideshow. 
2. When slideshowView is displayed (I assume first 3 images are preloaded).
3. Tap on slideshow view to enter full-screen controller
4. Swipe to 4th image
5. Exit fullScreenViewController
6. Slideshow view is now on 4th image index but the image is not displaying/rendering properly.
7. Now if swipe left/right again in slideshow view, images get displayed/rendered correctly again.

**Comment by mjrehder** [comment]
Hmm, this is odd. I fixed this issue (Issue #92) for some some time ago, but I can see in the code, that the fix was somehow removed again.
The ImageSlideShow::presentFullScreenController ought to contain this:
    open func presentFullScreenController(from controller:UIViewController) -> FullScreenSlideshowViewController {
        let fullscreen = FullScreenSlideshowViewController()
        fullscreen.pageSelected = {(page: Int) in
            // Before setting the new page, make sure that the current page image view is made visible again (altered by ZoomAnimator)
            if let ci = self.currentSlideshowItem {
                ci.imageView.alpha = 1.0
            }
            self.setCurrentPage(page, animated: false)
        }

This code was merged, but I can see from the current code, that it's gone.
Mistake, or should it have been fixed by another change?

**Comment by shawn-shen** [comment]
Hmm..Moving slideshow.setup from viewWillAppear to viewDidLoad seems fixed the issue. Closing this ticket for now.
