### ISSUE TITLE
Show more than one image for larger displays

### ISSUE THREAD

**Issue by jaybuangan** [zvonicek/ImageSlideshow#117]
I'm using this in an iPad app as well and was wondering if I can show more than one similar to how it's done in the App Store.

![screen shot 2017-01-24 at 2 21 06 pm](https://cloud.githubusercontent.com/assets/527997/22269510/7fb75518-e240-11e6-82db-ed762681a82c.png)

**Comment by zvonicek** [comment]
Hi, thanks for a nice suggestion. It is not currently possible, but I'd definitely like to explore this use case more. It'd be a nice addition to the library I guess.

**Comment by htarwara6245** [comment]
@jaybuangan , your suggestion is good but this library is only meant for one by one image slide show and full screen zoom feature. You can archive this by using collection view and custom layout with centered paging.

@zvonicek , since the request can be done by using collection view, so can you close it?

**Comment by zvonicek** [comment]
I'm closing this issue for now as it's currently out of the scope of the project. I'd still like to explore this case more, but there are bunch of tasks which have bigger priority than this.
