### ISSUE TITLE
imageslideshow issue

### ISSUE THREAD

**Issue by sidshah13** [zvonicek/ImageSlideshow#121]
Cannot invoke initializer for type 'ZoomAnimatedTransitioningDelegate' with an argument list of type '(slideshowView: ImageSlideshow!)'

**Comment by zvonicek** [comment]
I guess this is caused by upgrading from pre-1.0 version to 1.0. `ZoomAnimatedTransitioningDelegate` initializer now have init with two parameters: 
`public init(slideshowView: ImageSlideshow, slideshowController: FullScreenSlideshowViewController)` so please update your code to match this initializer.

**Comment by sidshah13** [comment]
how can i set customize height of imageslideview?
