### ISSUE TITLE
Unknown attribute 'objcMembers'

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [zvonicek/ImageSlideshow#235]
I have a legacy code and I can't update to Xcode 9.0 and I'm using Xcode 8.3.3 , 
when I compile the project I get this error 

> ActivityIndicator.swift:43:2: Unknown attribute 'objcMembers'

Swift version is 3.1 
and ImageSlideShow version is 1.5 

> pod 'ImageSlideshow', '~> 1.5'

also I got this error 

> FullScreenSlideshowViewController.swift:90:34: Value of type 'UIView' has no member 'safeAreaInsets'

and this one too 

> ImageSlideshow.swift:230:39: Value of type 'ImageSlideshow' has no member 'safeAreaInsets'

how I can solve these issues with  Xcode 8.3.3 and Swift 3.1

**Comment by zvonicek** [comment]
Hi, this is happening because of `safeAreaInsets` property that become available since iOS 11, so the code will not compile if your base SDK is iOS 10 or lower (Xcode 8 and lower). I recommend you to use version 1.3.2 (`pod 'ImageSlideshow', '~> 1.3.2'`) that has no reference to `safeAreaInsets` in it and should work well on Swift 3.1.
