### ISSUE TITLE
change scroll direction

### ISSUE THREAD

**Issue by ibrahim-zakarya** [zvonicek/ImageSlideshow#312]
is it possible to change the scroll direction, and if so, how to do that?

Thanks

**Comment by zvonicek** [comment]
Hi, that you mean support for LTR?

**Comment by lorencr7** [comment]
I think that what he meant was vertical image show instead of horizontal image show, with page indicator set up on vertical by default and vertical scrolling of images. Is it possible without having to modify the source code? As far as I can see, the contentSize of the scrollView is set on the method "layoutScrollView" but this function is not open and cannot be overriden by subclassing

**Comment by zvonicek** [comment]
It's not possible now, unfortunately. It would probably be slightly more complicated to implement.

**Comment by rferbesa** [comment]
Hi! Since I'd need this feature too (scroll images vertically), I've tried to subclass some classes, override layoutScrollView and other methods... but I haven't been able to have the desired behavior. The result is close to the desired one, but there are several glitches. The problem is that some methods that would need to be overridden are private so it's not possible.
Are you possibly thinking of adding this feature int he future? Or someone has managed to have the vertical scroll working and want to share the solution?
